# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Atata Tests

on:
  push:
    branches: [ "atata-development" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: AtataUITests
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: AtataUITests
      
    - name: Test
      run: dotnet test --verbosity normal AtataUITests\AtataUITests.csproj --filter "Category=AtataTestBoxTests"
