name: .NET Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./AqaPractice/AqaPractice.sln

    - name: Build the project
      run: dotnet build ./AqaPractice/AqaPractice.sln --configuration Debug

    - name: Run tests
      run: dotnet test --no-build --verbosity normal ./AqaPractice/bin/Debug/net8.0/AtataUITest.dll --filter "Category=TextBoxTests"