name: Playwright tests

on:
  push:
    branches: [ "playwright-development" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: PlaywrightUITests
      - name: Build
        run: dotnet build --no-restore
        working-directory: PlaywrightUITests
      - name: PWInstall
        run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
        working-directory: PlaywrightUITests
      - name: Test
        run: dotnet test PlaywrightUITests/PlaywrightUITests.csproj --filter "Category=UI"