name: PlayWright Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: PlaywrightUITests
        
      - name: Build
        run: dotnet build
        working-directory: PlaywrightUITests
        
      - name: Test
        run: dotnet test --verbosity normal PlaywrightUITests\PlaywrightUITests.csproj --filter "Category=PlayWrightTestBoxTests"